services:
  - type: web
    name: legalone-faq-api
    env: node
    buildCommand: |
      npm install
      npx playwright install --with-deps
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
